version: "3.8"

networks:
  laravel:

volumes:
  db-volume:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - laravel
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT:-33060}:3306
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-homestead}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - laravel
  npm:
    image: node:alpine
    container_name: npm
    tty: true
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
