version: "3.8"

networks:
  laravel:

volumes:
  db-volume:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - ./src:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT:-33060}:3306
    volumes:
      - db-volume:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-homestead}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - laravel

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html:cached
      - ./jobschedule/logs:/var/logs/jobschedule
    environment:
      TZ: "Asia/Tokyo"
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-homestead}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
    networks:
      - laravel
